# Generated by Django 4.2.25 on 2025-12-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_hours_per_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='proposal',
            name='availability',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract')], default='part-time', help_text="Freelancer's availability for this project", max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='portfolio_links',
            field=models.TextField(blank=True, help_text='Links to portfolio, GitHub, live demos, etc. (one per line)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposed_solution',
            field=models.TextField(blank=True, default='', help_text='Detailed explanation of how the freelancer will approach the project'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='relevant_skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of relevant skills'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('freelancer', 'project')},
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposal_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='attachments',
        ),
    ]
