# Generated by Django 4.2.25 on 2025-12-03 09:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_hours_per_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0002_alter_proposal_unique_together_proposal_availability_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='proposal',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('project', 'freelancer')},
        ),
        migrations.DeleteModel(
            name='ProposalAttachment',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='portfolio_links',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='proposed_solution',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='relevant_skills',
        ),
    ]
