# Generated by Django 4.2.25 on 2025-12-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clientprofile_active_jobs_and_more'),
        ('proposals', '0003_alter_proposal_unique_together_proposal_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='availability',
            field=models.CharField(blank=True, help_text='Availability selected in the proposal (e.g., 10–30 hrs/week)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='portfolio_links',
            field=models.TextField(blank=True, help_text='Portfolio URLs (one per line or comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposed_solution',
            field=models.TextField(blank=True, help_text='Detailed explanation of how the freelancer will approach the project', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='relevant_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills specifically highlighted for this proposal', related_name='proposals', to='users.skill'),
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposal_attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('is_resume', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
