# Generated by Django 4.2.25 on 2025-11-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('proposal', 'Proposal'), ('contract', 'Contract'), ('system', 'System'), ('workspace', 'Workspace'), ('payment', 'Payment'), ('review', 'Review')], max_length=20),
        ),
    ]
