# Generated by Django 4.2.25 on 2025-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration_estimate',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(choices=[('less_1_month', 'Less than 1 month'), ('1_3_months', '1 - 3 months'), ('3_6_months', '3 - 6 months'), ('more_6_months', 'More than 6 months')], default='less_1_month', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='fixed_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hourly_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hourly_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hours_per_week',
            field=models.CharField(choices=[('less_30', 'Less than 30 hrs/week'), ('more_30', 'More than 30 hrs/week')], default='less_30', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='job_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price')], default='fixed', max_length=10),
        ),
    ]
