# Generated by Django 4.2.25 on 2025-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_duration_estimate_project_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(choices=[('less_1_month', 'Less than 1 month'), ('1_3_months', '1 - 3 months'), ('3_6_months', '3 - 6 months'), ('6_plus_months', '6+ months')], default='less_1_month', max_length=20),
        ),
    ]
