# Generated by Django 4.2.25 on 2025-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
