# Generated by Django 4.2.26 on 2025-11-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_client_location_project_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_estimate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
