# Generated by Django 4.2.25 on 2025-11-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_duration_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hours_per_week',
            field=models.CharField(choices=[('less_10', 'Less than 10 hrs/week'), ('10_30', '10–30 hrs/week'), ('more_30', 'More than 30 hrs/week')], default='less_30', max_length=20),
        ),
    ]
