# Generated by Django 4.2.25 on 2025-12-08 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_hours_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_max',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='fixed_payment',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='hours_per_week',
            field=models.CharField(choices=[('less_10', 'Less than 10 hrs/week'), ('10_30', '10—30 hrs/week'), ('more_30', 'More than 30 hrs/week')], default='less_30', max_length=20),
        ),
    ]
