# Generated by Django 4.2.25 on 2025-11-17 09:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_alter_contract_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Response',
                'verbose_name_plural': 'Review Responses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified this review is legitimate'),
        ),
        migrations.AddField(
            model_name='review',
            name='project_title',
            field=models.CharField(blank=True, help_text='Title of project worked on', max_length=300),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('platform', 'Platform Review'), ('external', 'External Review')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_company',
            field=models.CharField(blank=True, help_text='Company/Organization of external reviewer', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(blank=True, help_text='Email of external reviewer (for verification)', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Name of external reviewer', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Token sent to reviewer email for verification', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='work_period',
            field=models.CharField(blank=True, help_text="e.g., 'Jan 2024 - Mar 2024'", max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Linked contract (for platform reviews)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(help_text='Person being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Reviewer (if registered user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', '-created_at'], name='contracts_r_reviewe_8c5dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_type', 'is_verified'], name='contracts_r_review__4dca75_idx'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='contracts.review'),
        ),
    ]
