# Generated by Django 4.2.25 on 2025-12-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_reviewresponse_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional contract attachment uploaded by the client.', null=True, upload_to='contracts/attachments/'),
        ),
    ]
