# Generated by Django 4.2.25 on 2025-12-04 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0006_contract_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review Response', 'verbose_name_plural': 'Review Responses'},
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='response_text',
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='work_period',
            field=models.CharField(blank=True, help_text="e.g. 'Jan 2024 - Mar 2024'", max_length=100),
        ),
    ]
