# Generated by Django 4.2.25 on 2025-12-04 18:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours worked (minimum 0.01 = 6 minutes)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField(help_text='Date work was performed')),
                ('description', models.TextField(blank=True, help_text='What work was done during this time')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='workspacetask',
            name='workspaces__workspa_b043b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='workspacetask',
            name='workspaces__deadlin_535a40_idx',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='freelancer',
            new_name='requested_by',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workspacetask',
            name='attachments',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_fully_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a specific task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='workspaces.workspacetask'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['workspace', 'is_approved'], name='workspaces__workspa_8eb179_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['date'], name='workspaces__date_e56b56_idx'),
        ),
    ]
