# Generated by Django 4.2.25 on 2025-12-04 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0002_timeentry_alter_taskcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='workspace',
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='requested_by',
            new_name='freelancer',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='is_fully_completed',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='workspaces.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workspacetask',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacetask',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name='workspacetask',
            index=models.Index(fields=['workspace', 'status'], name='workspaces__workspa_b043b4_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacetask',
            index=models.Index(fields=['deadline'], name='workspaces__deadlin_535a40_idx'),
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
