# Generated by Django 4.2.25 on 2025-12-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_jobapplicationattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
