# Generated by Django 4.2.25 on 2025-10-31 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_skill_options_skill_created_at_skill_is_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='custom_category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='experiences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='role_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PortfolioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolio_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_files', to='users.freelancerprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
