# Generated by Django 4.2.25 on 2025-11-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_freelancerprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='active_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='completed_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='completed_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='jobs_posted',
            field=models.IntegerField(default=0),
        ),
    ]
